# Generated by Django 5.2.6 on 2026-06-05 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='order_number', max_length=50, unique=True)),
                ('value', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Счётчик номеров',
                'verbose_name_plural': 'Счётчики номеров',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit', models.CharField(max_length=500, verbose_name='Комплект')),
                ('request_date', models.DateField(default=django.utils.timezone.localdate, editable=False, verbose_name='Дата обращения')),
                ('forecast_date', models.DateField(verbose_name='Прогнозируемая дата реализации')),
                ('order_number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('planned', 'В плане'), ('in_progress', 'В работе'), ('produced', 'Произведен'), ('cancelled', 'Отмена')], db_index=True, default='planned', max_length=16, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributor_orders', to='directories.organization', verbose_name='Дистрибьютор')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_orders', to='directories.employee', verbose_name='Менеджер')),
                ('participants', models.ManyToManyField(blank=True, related_name='participant_orders', to='directories.organization', verbose_name='Участники проекта')),
                ('potential_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='potential_user_orders', to='directories.organization', verbose_name='Потенциальный пользователь')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orders', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-order_number'],
            },
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Когда')),
                ('field', models.CharField(max_length=64, verbose_name='Поле')),
                ('field_label', models.CharField(blank=True, max_length=128, verbose_name='Название поля')),
                ('old_value', models.TextField(blank=True, verbose_name='Старое значение')),
                ('new_value', models.TextField(blank=True, verbose_name='Новое значение')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order', verbose_name='Заказ')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Изменение заказа',
                'verbose_name_plural': 'История изменений',
                'ordering': ['-changed_at'],
            },
        ),
    ]
