# Generated by Django 5.2.6 on 2026-06-05 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('rel_path', models.CharField(max_length=500, verbose_name='Путь')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Размер')),
                ('kind', models.CharField(choices=[('auto', 'Автоматически'), ('manual', 'Вручную')], default='auto', max_length=10, verbose_name='Тип')),
                ('status', models.CharField(choices=[('ok', 'Готова'), ('failed', 'Ошибка')], default='ok', max_length=10, verbose_name='Статус')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Резервная копия',
                'verbose_name_plural': 'Резервные копии',
                'ordering': ['-created_at'],
            },
        ),
    ]
