# Generated by Django 5.2.6 on 2026-06-05 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(db_index=True, verbose_name='Номер заказа')),
                ('original_name', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('stored_name', models.CharField(max_length=255, verbose_name='Имя файла на диске')),
                ('rel_path', models.CharField(max_length=500, verbose_name='Путь к файлу')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='Размер файла')),
                ('content_type', models.CharField(blank=True, max_length=120, verbose_name='MIME-тип')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_detached', models.BooleanField(default=False, verbose_name='Удалён из карточки')),
                ('detached_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления из карточки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='orders.order', verbose_name='Заказ')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл заказа',
                'verbose_name_plural': 'Файлы заказов',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
