# Generated by Django 5.2.6 on 2026-06-05 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Вход'), ('logout', 'Выход'), ('user_create', 'Создание пользователя'), ('user_update', 'Изменение пользователя'), ('user_block', 'Блокировка пользователя'), ('user_unblock', 'Разблокировка пользователя'), ('order_create', 'Создание заказа'), ('order_update', 'Изменение заказа'), ('status_change', 'Изменение статуса'), ('file_upload', 'Загрузка файла'), ('file_detach', 'Удаление файла из карточки'), ('backup_create', 'Создание резервной копии'), ('backup_restore', 'Восстановление из копии'), ('backup_delete', 'Удаление резервной копии')], max_length=32, verbose_name='Действие')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('target_type', models.CharField(blank=True, max_length=64, verbose_name='Тип объекта')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='ID объекта')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время (UTC)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ['-created_at'],
            },
        ),
    ]
