# Generated by Django 5.2.6 on 2026-06-05 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('type', models.CharField(choices=[('manager', 'Менеджер'), ('operator', 'Оператор'), ('director', 'Руководитель'), ('admin', 'Администратор'), ('other', 'Прочее')], db_index=True, default='other', max_length=16, verbose_name='Тип сотрудника')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='ИНН')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Наименование')),
                ('full_name', models.CharField(blank=True, max_length=1000, verbose_name='Полное наименование')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(blank=True, max_length=15, verbose_name='ОГРН')),
                ('address', models.CharField(blank=True, max_length=1000, verbose_name='Юридический адрес')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='Статус организации')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='Источник данных')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата последнего обновления')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['name', 'inn'],
            },
        ),
    ]
