# Generated by Django 5.2.6 on 2026-06-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(db_index=True, max_length=12, verbose_name='ИНН'),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(fields=('inn', 'kpp'), name='uniq_org_inn_kpp'),
        ),
    ]
